import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Providers from "../provider";
import { Toaster } from "@/components/ui/sonner"
import Navbar from "@/components/Navbar";
import "../globals.css"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Anonymous | Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
        <>
          <Navbar/>
          {children}
        </>
      
  );
}
